--js-runtimes node
--remote-components ejs:github
--no-check-certificate
--ffmpeg-location "C:\Users\GONI0\AppData\Local\Programs\Python\Python310\lib\site-packages\static_ffmpeg\bin\win32\ffmpeg.exe"
--format "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
